"""
Description:
Define, train, validate, and test a compact MCUNet-style neural
network for three-class image classification.

Classes:
- animal
- empty
- person

The model uses inverted residual blocks and depthwise separable
convolutions to reduce the number of parameters and operations.

This implementation follows MCUNet design principles, but it is not
an architecture generated by the official TinyNAS search framework.
"""

from pathlib import Path

import torch
from torch import nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau

from dataset import get_dataloaders


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

RESULTS_DIR = PROJECT_ROOT / "results" / "mcunet"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = RESULTS_DIR / "best_mcunet.pt"

IMAGE_SIZE = 48

EPOCHS = 100
LEARNING_RATE = 0.0003
WEIGHT_DECAY = 0.0001
DROPOUT = 0.20

EARLY_STOPPING_PATIENCE = 15
SCHEDULER_PATIENCE = 5


# ---------------------------------------------------------------------------
# Model components
# ---------------------------------------------------------------------------

class ConvBNActivation(nn.Sequential):
    """
    Convolution followed by batch normalization and ReLU6 activation.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int = 3,
        stride: int = 1,
        groups: int = 1,
        use_activation: bool = True,
    ) -> None:

        padding = kernel_size // 2

        layers: list[nn.Module] = [
            nn.Conv2d(
                in_channels=in_channels,
                out_channels=out_channels,
                kernel_size=kernel_size,
                stride=stride,
                padding=padding,
                groups=groups,
                bias=False,
            ),
            nn.BatchNorm2d(out_channels),
        ]

        if use_activation:
            layers.append(
                nn.ReLU6(inplace=True)
            )

        super().__init__(*layers)


class InvertedResidualBlock(nn.Module):
    """
    Lightweight inverted residual block.

    Structure:
    1. Pointwise expansion convolution.
    2. Depthwise spatial convolution.
    3. Pointwise projection convolution.
    4. Optional residual connection.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        stride: int,
        expansion_ratio: int,
    ) -> None:

        super().__init__()

        if stride not in {1, 2}:
            raise ValueError(
                f"Stride must be 1 or 2, but received {stride}."
            )

        hidden_channels = in_channels * expansion_ratio

        self.use_residual = (
            stride == 1
            and in_channels == out_channels
        )

        layers: list[nn.Module] = []

        # Pointwise expansion convolution.
        if expansion_ratio != 1:
            layers.append(
                ConvBNActivation(
                    in_channels=in_channels,
                    out_channels=hidden_channels,
                    kernel_size=1,
                    stride=1,
                )
            )

        # Depthwise convolution.
        layers.append(
            ConvBNActivation(
                in_channels=hidden_channels,
                out_channels=hidden_channels,
                kernel_size=3,
                stride=stride,
                groups=hidden_channels,
            )
        )

        # Pointwise projection convolution without activation.
        layers.append(
            ConvBNActivation(
                in_channels=hidden_channels,
                out_channels=out_channels,
                kernel_size=1,
                stride=1,
                use_activation=False,
            )
        )

        self.block = nn.Sequential(*layers)

    def forward(
        self,
        inputs: torch.Tensor,
    ) -> torch.Tensor:
        """Compute the block output."""

        outputs = self.block(inputs)

        if self.use_residual:
            outputs = outputs + inputs

        return outputs


# ---------------------------------------------------------------------------
# MCUNet-style model
# ---------------------------------------------------------------------------

class MCUNet(nn.Module):
    """
    Compact MCUNet-style classifier for 48 x 48 RGB images.
    """

    def __init__(
        self,
        num_classes: int,
        dropout: float = 0.20,
    ) -> None:

        super().__init__()

        self.features = nn.Sequential(

            # Input: 3 x 48 x 48
            ConvBNActivation(
                in_channels=3,
                out_channels=16,
                kernel_size=3,
                stride=2,
            ),

            # Output: 16 x 24 x 24
            InvertedResidualBlock(
                in_channels=16,
                out_channels=16,
                stride=1,
                expansion_ratio=1,
            ),

            # Output: 24 x 12 x 12
            InvertedResidualBlock(
                in_channels=16,
                out_channels=24,
                stride=2,
                expansion_ratio=3,
            ),

            InvertedResidualBlock(
                in_channels=24,
                out_channels=24,
                stride=1,
                expansion_ratio=3,
            ),

            # Output: 32 x 6 x 6
            InvertedResidualBlock(
                in_channels=24,
                out_channels=32,
                stride=2,
                expansion_ratio=3,
            ),

            InvertedResidualBlock(
                in_channels=32,
                out_channels=32,
                stride=1,
                expansion_ratio=3,
            ),

            # Output: 48 x 3 x 3
            InvertedResidualBlock(
                in_channels=32,
                out_channels=48,
                stride=2,
                expansion_ratio=4,
            ),

            InvertedResidualBlock(
                in_channels=48,
                out_channels=48,
                stride=1,
                expansion_ratio=4,
            ),

            # Final pointwise convolution.
            ConvBNActivation(
                in_channels=48,
                out_channels=96,
                kernel_size=1,
                stride=1,
            ),
        )

        self.pool = nn.AdaptiveAvgPool2d(
            output_size=(1, 1)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(p=dropout),
            nn.Linear(96, num_classes),
        )

        self.initialize_weights()

    def initialize_weights(self) -> None:
        """Initialize convolutional and linear layer weights."""

        for module in self.modules():

            if isinstance(module, nn.Conv2d):
                nn.init.kaiming_normal_(
                    module.weight,
                    mode="fan_out",
                    nonlinearity="relu",
                )

            elif isinstance(module, nn.BatchNorm2d):
                nn.init.ones_(module.weight)
                nn.init.zeros_(module.bias)

            elif isinstance(module, nn.Linear):
                nn.init.normal_(
                    module.weight,
                    mean=0.0,
                    std=0.01,
                )

                if module.bias is not None:
                    nn.init.zeros_(module.bias)

    def forward(
        self,
        images: torch.Tensor,
    ) -> torch.Tensor:
        """Return the classification logits."""

        features = self.features(images)
        pooled_features = self.pool(features)
        logits = self.classifier(pooled_features)

        return logits


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def select_device() -> torch.device:
    """Select the best available computing device."""

    if torch.backends.mps.is_available():
        return torch.device("mps")

    if torch.cuda.is_available():
        return torch.device("cuda")

    return torch.device("cpu")


def count_parameters(model: nn.Module) -> int:
    """Return the number of trainable parameters."""

    return sum(
        parameter.numel()
        for parameter in model.parameters()
        if parameter.requires_grad
    )


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_one_epoch(
    model: nn.Module,
    loader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> tuple[float, float]:
    """Train the model for one epoch."""

    model.train()

    total_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    for images, labels in loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        logits = model(images)
        loss = criterion(logits, labels)

        loss.backward()
        optimizer.step()

        batch_size = images.size(0)

        total_loss += loss.item() * batch_size
        total_samples += batch_size

        predictions = logits.argmax(dim=1)

        correct_predictions += (
            predictions == labels
        ).sum().item()

    average_loss = total_loss / total_samples
    accuracy = correct_predictions / total_samples

    return average_loss, accuracy


# ---------------------------------------------------------------------------
# Validation and test
# ---------------------------------------------------------------------------

def evaluate(
    model: nn.Module,
    loader,
    criterion: nn.Module,
    device: torch.device,
) -> tuple[float, float]:
    """Evaluate the model without updating its parameters."""

    model.eval()

    total_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(device)
            labels = labels.to(device)

            logits = model(images)
            loss = criterion(logits, labels)

            batch_size = images.size(0)

            total_loss += loss.item() * batch_size
            total_samples += batch_size

            predictions = logits.argmax(dim=1)

            correct_predictions += (
                predictions == labels
            ).sum().item()

    average_loss = total_loss / total_samples
    accuracy = correct_predictions / total_samples

    return average_loss, accuracy


# ---------------------------------------------------------------------------
# Checkpoint
# ---------------------------------------------------------------------------

def save_checkpoint(
    model: nn.Module,
    class_names: list[str],
    epoch: int,
    validation_loss: float,
    validation_accuracy: float,
) -> None:
    """Save the best MCUNet checkpoint."""

    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "class_names": class_names,
            "image_size": IMAGE_SIZE,
            "dropout": DROPOUT,
            "epoch": epoch,
            "validation_loss": validation_loss,
            "validation_accuracy": validation_accuracy,
            "trainable_parameters": count_parameters(model),
        },
        MODEL_PATH,
    )


# ---------------------------------------------------------------------------
# Main procedure
# ---------------------------------------------------------------------------

def main() -> None:
    """Train and test the MCUNet-style model."""

    (
        train_loader,
        val_loader,
        test_loader,
        class_names,
    ) = get_dataloaders()

    # Verify the image size returned by dataset.py.
    sample_images, _ = next(iter(train_loader))

    returned_height = sample_images.shape[2]
    returned_width = sample_images.shape[3]

    if (
        returned_height != IMAGE_SIZE
        or returned_width != IMAGE_SIZE
    ):
        raise ValueError(
            "Incorrect image size returned by the DataLoader. "
            f"Expected {IMAGE_SIZE} x {IMAGE_SIZE}, "
            f"but received {returned_height} x {returned_width}."
        )

    device = select_device()

    model = MCUNet(
        num_classes=len(class_names),
        dropout=DROPOUT,
    ).to(device)

    criterion = nn.CrossEntropyLoss()

    optimizer = AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )

    scheduler = ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=SCHEDULER_PATIENCE,
        min_lr=1e-6,
    )

    print("\nMCUNet-style training")
    print("=" * 70)
    print(f"Device: {device}")
    print(f"Classes: {class_names}")
    print(f"Training images: {len(train_loader.dataset)}")
    print(f"Validation images: {len(val_loader.dataset)}")
    print(f"Test images: {len(test_loader.dataset)}")
    print(f"Input size: {IMAGE_SIZE} x {IMAGE_SIZE}")
    print(f"Trainable parameters: {count_parameters(model):,}")
    print(f"Checkpoint: {MODEL_PATH}")
    print("=" * 70)

    best_validation_loss = float("inf")
    epochs_without_improvement = 0

    for epoch in range(1, EPOCHS + 1):

        train_loss, train_accuracy = train_one_epoch(
            model=model,
            loader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            device=device,
        )

        validation_loss, validation_accuracy = evaluate(
            model=model,
            loader=val_loader,
            criterion=criterion,
            device=device,
        )

        scheduler.step(validation_loss)

        current_learning_rate = (
            optimizer.param_groups[0]["lr"]
        )

        print(
            f"Epoch {epoch:03d}/{EPOCHS} | "
            f"train loss: {train_loss:.4f} | "
            f"train acc: {train_accuracy:.4f} | "
            f"val loss: {validation_loss:.4f} | "
            f"val acc: {validation_accuracy:.4f} | "
            f"lr: {current_learning_rate:.7f}"
        )

        if validation_loss < best_validation_loss:

            best_validation_loss = validation_loss
            epochs_without_improvement = 0

            save_checkpoint(
                model=model,
                class_names=class_names,
                epoch=epoch,
                validation_loss=validation_loss,
                validation_accuracy=validation_accuracy,
            )

            print(
                f"  Saved best model: {MODEL_PATH}"
            )

        else:
            epochs_without_improvement += 1

        if (
            epochs_without_improvement
            >= EARLY_STOPPING_PATIENCE
        ):
            print(
                f"\nEarly stopping after {epoch} epochs."
            )
            break

    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"No checkpoint was created: {MODEL_PATH}"
        )

    checkpoint = torch.load(
        MODEL_PATH,
        map_location=device,
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    test_loss, test_accuracy = evaluate(
        model=model,
        loader=test_loader,
        criterion=criterion,
        device=device,
    )

    model_size_mb = (
        MODEL_PATH.stat().st_size / (1024 ** 2)
    )

    print("\nBest validation checkpoint")
    print("=" * 70)
    print(f"Epoch: {checkpoint['epoch']}")
    print(
        f"Validation loss: "
        f"{checkpoint['validation_loss']:.4f}"
    )
    print(
        f"Validation accuracy: "
        f"{checkpoint['validation_accuracy']:.4f}"
    )

    print("\nFinal test results")
    print("=" * 70)
    print(f"Test loss: {test_loss:.4f}")
    print(f"Test accuracy: {test_accuracy:.4f}")
    print(
        f"Trainable parameters: "
        f"{count_parameters(model):,}"
    )
    print(f"Checkpoint size: {model_size_mb:.2f} MB")
    print(f"Saved checkpoint: {MODEL_PATH}")


if __name__ == "__main__":
    main()